DROP TRIGGER IF EXISTS `Appteachers`.`Subjects_BEFORE_INSERT_SUB_NAME`;
CREATE DEFINER = CURRENT_USER TRIGGER `Appteachers`.`Subjects_BEFORE_INSERT_SUB_NAME` BEFORE INSERT ON `Subjects` FOR EACH ROW
SET NEW.subj_name = UPPER(NEW.subj_name);