DROP TRIGGER IF EXISTS `Appteachers`.`Teachers_BEFORE_INSERT_ZIP`;
CREATE DEFINER = CURRENT_USER TRIGGER `Appteachers`.`Teachers_BEFORE_INSERT_ZIP` 
BEFORE INSERT ON `Appteachers`.`Teachers` FOR EACH ROW
SET NEW.teach_zip = UPPER(NEW.teach_zip);