DROP TRIGGER IF EXISTS `Appteachers`.`Users_BEFORE_INSERT_USER_DELETED`;
CREATE DEFINER = CURRENT_USER TRIGGER `Appteachers`.`Users_BEFORE_INSERT_USER_DELETED` BEFORE INSERT ON `Users` FOR EACH ROW
IF NEW.user_deleted <> "SI" THEN SET NEW.user_deleted = "NO"
END IF;