INSERT INTO AppTeachers.Subjects(subj_id, subj_name) VALUES(null,'MATES');
INSERT INTO AppTeachers.Subjects(subj_id, subj_name) VALUES(null,'LENGUA');
INSERT INTO AppTeachers.Subjects(subj_id, subj_name) VALUES(null,'JAVASCRIPT');
INSERT INTO AppTeachers.Subjects(subj_id, subj_name) VALUES(null,'ANGULAR');
INSERT INTO AppTeachers.Subjects(subj_id, subj_name) VALUES(null,'MYSQL');
INSERT INTO AppTeachers.Subjects(subj_id, subj_name) VALUES(null,'NODE');
INSERT INTO AppTeachers.Subjects(subj_id, subj_name) VALUES(null,'PYTHON');
INSERT INTO AppTeachers.Subjects(subj_id, subj_name) VALUES(null,'HTML');
INSERT INTO AppTeachers.Subjects(subj_id, subj_name) VALUES(null,'CSS');